apiVersion: argoproj.io/v1alpha1
kind: Workflow
namespace: workflows
metadata:
  name: stage3-build
spec:
  entrypoint: build-push
  volumes:
  - name: docker-config
    secret:
      secretName: systoleos-herbie-pull-secret
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: build-push
    steps:
    - - name: build
        template: kaniko-build
  - name: kaniko-build
    inputs:
      parameters:
      - name: registry
        value: quay.io/systoleos/stage3
      - name: tag
        value: latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      command: ["/bin/sh", "-c"]
      args:
        - >
          /kaniko/executor --context=dir://workspace
          --dockerfile=https://raw.githubusercontent.com/SystoleOS/docker/main/SystoleOS/stage3/Dockerfile
          --destination={{inputs.parameters.registry}}:{{inputs.parameters.tag}}
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
